POST http://localhost:3000/api/wanaka/group HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MzgwMDY2NTMsInVzZXIiOiI5MjUyNTg0MCJ9.cN2aLh05XZ3abZ0xqIATjniTdQJO0HbMAziflsLDO2o

{
  "userid": "92525840",
  "groupid": "Marcos Tirao"
}